# Generated by Django 4.2.7 on 2023-12-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
