# Generated by Django 4.2.7 on 2024-02-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
